Uchet/Models/Expense.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Uchet.Models
{
    public class Expense
    {
        public int Id { get; set; }
        [Display(Name = "Наименование")]
        [Required(ErrorMessage = "Наименование не указано")]
        public string Name { get; set; }

        [Display(Name = "Дата прихода")]
        [Required(ErrorMessage = "Дата не указана")]
        public DateTime Date { get; set; }

        [Display(Name = "Накладная")]
        [Required(ErrorMessage = "Наименование не указано")]
        public string Invoice { get; set; }

        [Display(Name = "Поставщик")]
        [Required(ErrorMessage = "Поставщик не указан")]
        public string Provider { get; set; }

        [Display(Name = "Точка учета")]
        [Required(ErrorMessage = "Точка учета не указана")]
        public string ShippingAccountingPoint { get; set; }

        [Display(Name = "Точка учета")]
        [Required(ErrorMessage = "Точка учета не указана")]
        public string DeliveryAccountingPoint { get; set; }

        [Display(Name = "Покупатель")]
        [Required(ErrorMessage = "Покупатель не указан")]
        public string Byer { get; set; }


        public string Unit { get; set; }

        [Display(Name = "Количество")]
        [Required(ErrorMessage = "Количество не указано")]
        public int Quantity { get; set; }

        [Display(Name = "Цена")]
        [Required(ErrorMessage = "Цена не указана")]
        public float Price { get; set; }

        public float Cost { get; set; }
    }
}

Uchet/Controllers/ExpenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Uchet.Models;
using System.Data.Entity;

namespace Uchet.Controllers
{
    public class ExpenseController : Controller
    {
        Context db = new Context();

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Message = "Расход";
            List<ExpenseList> expenseList = new List<ExpenseList>();
            var loadDb = db.Expense;
            foreach (var item in loadDb)
            {
                expenseList.Add(new ExpenseList()
                {
                    Id = item.Id,
                    Nomenclature = db.Nomenclature.Find(item.Nomenclature).Name,
                    Date = item.Date,
                    Invoice = item.Invoice,
                    ShippingAccountingPoint = db.AccountingPoints.Find(item.ShippingAccountingPoint).Name,
                    DeliveryAccountingPoint = db.AccountingPoints.Find(item.DeliveryAccountingPoint).Name,
                    Buyer = db.Buyer.Find(item.Buyer).Name,
                    Quantity = item.Quantity,
                    Price = item.Price
                });
            }

            ViewBag.Expense = expenseList;
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            var nomenclature = new List<object>();
            foreach (var item in db.Nomenclature.OrderBy(s => s.Name))
            {
                nomenclature.Add(new { key = item.Id, label = item.Name });
            }
            var accountingpoints = new List<object>();
            foreach (var item in db.AccountingPoints.OrderBy(s => s.Name))
            {
                accountingpoints.Add(new { key = item.Id, label = item.Name });
            }
            var buyer = new List<object>();
            foreach (var item in db.Buyer.OrderBy(s => s.Name))
            {
                buyer.Add(new { key = item.Id, label = item.Name });
            }
            ViewBag.Nomenclature = new SelectList(nomenclature, "key", "label", null);
            ViewBag.ShippingAccountingPoint = new SelectList(accountingpoints, "key", "label", null);
            ViewBag.DeliveryAccountingPoint = new SelectList(accountingpoints, "key", "label", null);
            ViewBag.Buyer = new SelectList(buyer, "key", "label", null);
            return PartialView("Create");
        }

        [HttpPost]
        public ActionResult Create(Expense expense)
        {
            if (ModelState.IsValid)
            {
                db.Expense.Add(expense);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var expense = db.Expense.Find(id);

            if (expense != null)
            {
                return PartialView("Edit", expense);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Expense expense)
        {
            if (ModelState.IsValid)
            {
                db.Entry(expense).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var expense = db.Expense.Find(id);
            if (id == null)
            {
                return HttpNotFound();
            }
            if (expense != null)
            {
                return PartialView("Delete", expense);
            }
            return View("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteRecord(int? id)
        {
            var expense = db.Expense.Find(id);
            if (id == null)
            {
                return HttpNotFound();
            }
            if (expense != null)
            {
                db.Expense.Remove(expense);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Uchet/Controllers/ProfitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Uchet.Models;
using System.Data.Entity;

namespace Uchet.Controllers
{
    public class ProfitController : Controller
    {
        Context db = new Context();

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Message = "Поступления";
            List<ProfitList> profitList = new List<ProfitList>();
            var loadDb = db.Profit;
            foreach (var item in loadDb)
            {
                profitList.Add(new ProfitList()
                {
                    Id = item.Id,
                    Nomenclature = db.Nomenclature.Find(item.Nomenclature).Name,
                    Date = item.Date,
                    Invoice = item.Invoice,
                    Provider = db.Providers.Find(item.Provider).Name,
                    AccountingPoint = db.AccountingPoints.Find(item.AccountingPoint).Name,
                    Quantity = item.Quantity,
                    Price = item.Price
                });
            }

            ViewBag.Profit = profitList;
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            var nomenclature = new List<object>();
            var i = 1;
            foreach (var item in db.Nomenclature.OrderBy(s => s.Name))
            {
                nomenclature.Add(new { key = i, label = item.Name });
                i++;
            }
            i = 1;
            var providers = new List<object>();
            foreach (var item in db.Providers.OrderBy(s => s.Name))
            {
                providers.Add(new { key = i, label = item.Name });
                i++;
            }
            i = 1;
            var accountingpoints = new List<object>();
            foreach (var item in db.AccountingPoints.OrderBy(s => s.Name))
            {
                accountingpoints.Add(new { key = i, label = item.Name });
                i++;
            }
            ViewBag.Nomenclature = new SelectList(nomenclature, "key", "label", null);
            ViewBag.Provider = new SelectList(providers, "key", "label", null);
            ViewBag.AccountingPoint = new SelectList(accountingpoints, "key", "label", null);
            return PartialView("Create");
        }

        [HttpPost]
        public ActionResult Create(Profit profit)
        {
            if (ModelState.IsValid)
            {
                db.Profit.Add(profit);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var profit = db.Profit.Find(id);

            if (profit != null)
            {
                return PartialView("Edit", profit);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Profit profit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(profit).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var profit = db.Profit.Find(id);
            if (id == null)
            {
                return HttpNotFound();
            }
            if (profit != null)
            {
                return PartialView("Delete", profit);
            }
            return View("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteRecord(int? id)
        {
            var profit = db.Profit.Find(id);
            if (id == null)
            {
                return HttpNotFound();
            }
            if (profit != null)
            {
                db.Profit.Remove(profit);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Uchet/Views/Expense/Create.cshtml
@model Uchet.Models.Expense

<div class="modal-content">
    <div class="modal-header d-flex justify-content-center">
        <h4>Новая запись</h4>
    </div>
    @using (Html.BeginForm())
    {
    <div class="modal-body">

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Nomenclature)
            @Html.DropDownList("Nomenclature", ViewBag.Nomenclature as SelectList, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nomenclature, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Date)
            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Invoice)
            @Html.EditorFor(model => model.Invoice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Invoice, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ShippingAccountingPoint)
            @Html.DropDownList("ShippingAccountingPoint", ViewBag.ShippingAccountingPoint as SelectList, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ShippingAccountingPoint, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryAccountingPoint)
            @Html.DropDownList("DeliveryAccountingPoint", ViewBag.DeliveryAccountingPoint as SelectList, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DeliveryAccountingPoint, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Buyer)
            @Html.DropDownList("Buyer", ViewBag.Buyer as SelectList, String.Empty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Buyer, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Quantity)
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Price)
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>


    </div>
    <div class="modal-footer d-flex justify-content">
        <input type="submit" class="btn btn-outline-success" value="Создать" />
        <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Отмена</button>
    </div>
    }
</div>
@Scripts.Render("~/bundles/jqueryval")

Uchet/Views/Expense/Delete.cshtml
<div class="modal-content">
    <div class="modal-header d-flex justify-content-center">
        <h4>Вы действительно хотите удалить данную запись?</h4>
    </div>
    <div class="modal-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="d-flex justify-content">
                <input type="submit" class="btn btn-outline-success" value="Удалить" />
                <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Отмена</button>
            </div>

        }
    </div>
</div>

Uchet/Views/Expense/Edit.cshtml
@model Uchet.Models.Nomenclature

<div class="modal-content">
    <div class="modal-header d-flex justify-content-center">
        <h4>Редактировать запись</h4>
    </div>
    @using (Html.BeginForm())
    {
    <div class="modal-body">

        @Html.AntiForgeryToken()
        @Html.HiddenFor(с => с.Id)
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name)
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Code)
            @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Sort)
            @Html.EditorFor(model => model.Sort, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sort, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Unit)
            @Html.EditorFor(model => model.Unit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Unit, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Property)
            @Html.EditorFor(model => model.Property, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Property, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Comment)
            @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
        </div>


    </div>
        <div class="modal-footer d-flex justify-content">
            <input type="submit" class="btn btn-outline-success" value="Создать" />
            <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Отмена</button>
        </div>
    }
</div>
@Scripts.Render("~/bundles/jqueryval")

Uchet/Views/Expense/Index.cshtml
@{
    ViewBag.Title = "Расход";
}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">@ViewBag.Message</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group" role="group" aria-label="First group">
            @Html.ActionLink("Новая запись", "Create", "Expense", new { }, new { @class = "viewDialog btn btn-sm btn-primary", data_dialog_title = "Создание записи" })
        </div>
    </div>
</div>

<div>
    <table id="DTable" class="display compact stripe" style="width:100%">
        <thead>
            <tr>
                <th>№</th>
                <th>Наименование</th>
                <th>Дата</th>
                <th>№ накладной</th>
                <th>Точка отгрузки</th>
                <th>Точка поставки</th>
                <th>Покупатель</th>
                <th>Кол-во</th>
                <th>Цена</th>
                <th></th>
                <th></th>
                @*<th></th>*@
            </tr>
        </thead>
        @{
            int i = 1;
        }
        @foreach (var item in ViewBag.Expense)
        {

        <tr>
            <td>@i</td>
            <td>@item.Nomenclature</td>
            <td>@item.Date</td>
            <td>@item.Invoice</td>
            <td>@item.ShippingAccountingPoint</td>
            <td>@item.DeliveryAccountingPoint</td>
            <td>@item.Buyer</td>
            <td>@item.Quantity</td>
            <td>@item.Price</td>
            <td>
                @*
            @Html.ActionLink("Редактировать", "Edit", "Profit", new { id = item.Id },
                       new { @class = "viewDialog edit", title ="Редактировать" })*@
            </td>
            <td>
                @Html.ActionLink("Удалить", "Delete", "Profit", new { id = item.Id },
                           new { @class = "viewDialog", title = "Удалить" })
            </td>
        </tr>
        i++;
    }

    </table>
</div>