Uchet/Models/Providers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Uchet.Models
{
    public class Providers : Partner
    {
        [Display(Name = "Юридический адрес")]
        public string LegalAddress { get; set; }

        [Display(Name = "Адрес")]
        public string PhysicalAddress { get; set; }
    }
}

Uchet/Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Uchet.Models;
using System.Data.Entity;

namespace Uchet.Controllers
{
    public class ProvidersController : Controller
    {
        Context db = new Context();

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Message = "Поставщики";
            ViewBag.Providers = db.Providers;
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {  
            return PartialView("Create");
        }

        [HttpPost]
        public ActionResult Create(Providers provider)
        {           
            if (ModelState.IsValid)
            {
                db.Providers.Add(provider);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var providers = db.Providers.Find(id);

            if (providers != null)
            {
                return PartialView("Edit", providers);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Providers providers)
        {
            if (ModelState.IsValid)
            {
                db.Entry(providers).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var providers = db.Providers.Find(id);
            if (id == null)
            {
                return HttpNotFound();
            }
            if (providers != null)
            {
                return PartialView("Delete", providers);
            }
            return View("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteRecord(int? id)
        {
            var providers = db.Providers.Find(id);
            if (id == null)
            {
                return HttpNotFound();
            }
            if (providers != null)
            {
                db.Providers.Remove(providers);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Uchet/Views/Providers/Index.cshtml
@{
    ViewBag.Title = "Поставщики";
}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">@ViewBag.Message</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group" role="group" aria-label="First group">
            @Html.ActionLink("Новая запись", "Create", "Providers", new { }, new { @class = "viewDialog btn btn-sm btn-primary", data_dialog_title = "Создание записи" })
        </div>
    </div>
</div>
    <div>
        <table id="DTable" class="display compact stripe" style="width:100%">
            <thead>
                <tr>
                    <th>№</th>
                    <th>Наименование</th>
                    <th>Код</th>                    
                    <th>Юридический адрес</th>
                    <th>Адрес</th>
                    <th>Комментарий</th>                    
                    <th></th>
                    <th></th>                    
                </tr>
            </thead>

            @{
                int i = 1;               
            }
            @foreach (var item in ViewBag.Providers)
            {
                
            <tr>
                <td>@i</td>
                <td>@item.Name</td>
                <td>@item.Code</td>
                <td>@item.LegalAddress</td>
                <td>@item.PhysicalAddress</td>
                <td>@item.Comment</td>                
                <td>
                    @Html.ActionLink("Редактировать", "Edit", "Providers", new { id = item.Id },
                               new { @class = "viewDialog edit", title ="Редактировать" })
                </td>
                <td>
                    @Html.ActionLink("Удалить", "Delete", "Providers", new { id = item.Id },
                               new { @class = "viewDialog", title = "Удалить" })
                </td>
            </tr>
                i++;
            }

        </table>
    </div>