Uchet/Models/Buyer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Uchet.Models
{
    public class Buyer : Partner
    {
        [Display(Name = "Адрес")]
        public string PhysicalAddress { get; set; }
    }
}

Uchet/Controllers/BuyerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Uchet.Models;
using System.Data.Entity;

namespace Uchet.Controllers
{
    public class BuyerController : Controller
    {
        Context db = new Context();

        [HttpGet]
        public ActionResult Index()
        {
            ViewBag.Message = "Покупатели";
            ViewBag.Buyer = db.Buyer;
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return PartialView("Create");
        }

        [HttpPost]
        public ActionResult Create(Buyer buyer)
        {
            if (ModelState.IsValid)
            {
                db.Buyer.Add(buyer);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            var buyer = db.Buyer.Find(id);

            if (buyer != null)
            {
                return PartialView("Edit", buyer);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Buyer buyer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(buyer).State = EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var buyer = db.Buyer.Find(id);
            if (id == null)
            {
                return HttpNotFound();
            }
            if (buyer != null)
            {
                return PartialView("Delete", buyer);
            }
            return View("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteRecord(int? id)
        {
            var buyer = db.Buyer.Find(id);
            if (id == null)
            {
                return HttpNotFound();
            }
            if (buyer != null)
            {
                db.Buyer.Remove(buyer);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Uchet/Views/Buyer/Create.cshtml
@model Uchet.Models.Buyer

<div class="modal-content">
    <div class="modal-header d-flex justify-content-center">
        <h4>Новая запись</h4>
    </div>
    @using (Html.BeginForm())
    {
        <div class="modal-body">

            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true)
            <div class="form-group">
                @Html.LabelFor(model => model.Name)
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Code)
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.PhysicalAddress)
                @Html.EditorFor(model => model.PhysicalAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhysicalAddress, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Comment)
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>          


        </div>
        <div class="modal-footer d-flex justify-content">
            <input type="submit" class="btn btn-outline-success" value="Создать" />
            <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Отмена</button>
        </div>
    }
</div>
@Scripts.Render("~/bundles/jqueryval")

Uchet/Views/Buyer/Edit.cshtml
@model Uchet.Models.Buyer

<div class="modal-content">
    <div class="modal-header d-flex justify-content-center">
        <h4>Редактировать запись</h4>
    </div>
    @using (Html.BeginForm())
    {
    <div class="modal-body">

        @Html.AntiForgeryToken()
        @Html.HiddenFor(с => с.Id)
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name)
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Code)
            @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PhysicalAddress)
            @Html.EditorFor(model => model.PhysicalAddress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhysicalAddress, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Comment)
            @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
        </div>


    </div>
        <div class="modal-footer d-flex justify-content">
            <input type="submit" class="btn btn-outline-success" value="Создать" />
            <button type="button" class="btn btn-outline-primary" data-dismiss="modal">Отмена</button>
        </div>
    }
</div>
@Scripts.Render("~/bundles/jqueryval")

Uchet/Views/Buyer/Index.cshtml
@{
    ViewBag.Title = "Покупатели";
}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">@ViewBag.Message</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group" role="group" aria-label="First group">
            @Html.ActionLink("Новая запись", "Create", "Buyer", new { }, new { @class = "viewDialog btn btn-sm btn-primary", data_dialog_title = "Создание записи" })
        </div>
    </div>
</div>

<div>
    <table id="DTable" class="display compact stripe" style="width:100%">
        <thead>
            <tr>
                <th>№</th>
                <th>Наименование</th>
                <th>Код</th>
                <th>Адрес</th>
                <th>Комментарий</th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        @{
            int i = 1;
        }
        @foreach (var item in ViewBag.Buyer)
        {

            <tr>
                <td>@i</td>
                <td>@item.Name</td>
                <td>@item.Code</td>
                <td>@item.PhysicalAddress</td>
                <td>@item.Comment</td>
                <td>
                    @Html.ActionLink("Редактировать", "Edit", "Buyer", new { id = item.Id },
                               new { @class = "viewDialog edit", title ="Редактировать" })
                </td>
                <td>
                    @Html.ActionLink("Удалить", "Delete", "Buyer", new { id = item.Id },
                               new { @class = "viewDialog", title = "Удалить" })
                </td>
            </tr>
            i++;
        }

    </table>
</div>